import type { Metadata } from 'next'
import './globals.css'
import { fonts } from '@/lib/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className={fonts} lang="en" suppressHydrationWarning>
      <body>{children}</body>
    </html>
  )
}
